FROM registry.cn-shanghai.aliyuncs.com/c7n/javabase:0.9.0
WORKDIR /choerodon
COPY app.jar hzero-register.jar
COPY dist dist
RUN chmod +x /choerodon/dist/env.sh \
    && chown -R www-data:www-data /choerodon
USER 33
CMD /choerodon/dist/env.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /choerodon/hzero-register.jar